#!/bin/bash --norc

#find external/x86_64-unknown-linux-gnu -name "*-gcc"
#LD_LIBRARY_PATH="external/com_bootlin_toolchains_gcc_7_3_0/x86_64-buildroot-linux-gnu/sysroot/lib:external/com_bootlin_toolchains_gcc_7_3_0/libexec/gcc/x86_64-buildroot-linux-gnu/7.3.0:$LD_LIBRARY_PATH" \
#external/com_bootlin_toolchains_gcc_7_3_0/x86_64-buildroot-linux-gnu/bin:external/com_bootlin_toolchains_gcc_7_3_0/bin:
#PATH="external/com_bootlin_toolchains_gcc_7_3_0/libexec/gcc/x86_64-buildroot-linux-gnu/7.3.0:$PATH" \
exec \
    external/x86_64_unknown_linux_gnu_gcc_730/bin/x86_64-unknown-linux-gnu-gcc \
    "$@"
